[package]
name = "lkp-submit"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anstyle = "=1.0.10"
anyhow = "1.0.93"
basic-toml = "0.1.9"
directories = "5.0.1"
serde = { version = "1.0.215", features = ["derive"] }
tempfile = "3.14.0"
